Repository microsoft/electionguard-python, pull requests merged in 2020-07, with the labels that each got.

#77 🗳 Election Artifacts
  .gitignore
  src/electionguard/election.py
  src/electionguard/group.py
  src/electionguard/guardian.py
  src/electionguard/key_ceremony.py
  src/electionguard/logs.py
  src/electionguard/publish.py
  src/electionguard/serializable.py
  stubs/gmpy2.pyi
  tests/integration/test_end_to_end_election.py
  tests/test_publish.py
  tests/test_serializable.py
Labels: enhancement

#98 Fix typographical errors on the documentation
  README.md
  docs/0_Configure_Election.md
  docs/1_Key_Ceremony.md
  docs/2_Encrypt_Ballots.md
  docs/3_Cast_and_Spoil.md
  docs/4_Decrypt_Tally.md
  docs/Design_and_Architecture.md
  docs/Project_Workflow.md
  docs/index.md
Labels: community

#108 change README credits for Dan Wallach
  README.md
Labels: community

#104 Remove RSA from certain tests and CI for speed
  src/electionguard/decryption.py
  src/electionguard/decryption_mediator.py
  src/electionguard/key_ceremony_mediator.py
  tests/test_decryption_mediator.py
  tests/test_guardian.py
  tests/test_key_ceremony.py
  tests/test_key_ceremony_mediator.py
Labels: enhancement

#81 📝 Add Sample Election Manifest
  Makefile
  README.md
  data/ballot_in_simple.json
  data/election_manifest_simple.json
  data/hamilton-county/election_manifest.json
  data/plaintext_ballots_simple.json
  docs/0_Configure_Election.md
  docs/Election_Manifest.md
  docs/index.md
  electionguard-logo-large.png
  electionguard-logo-small.png
  mkdocs.yml
  src/electionguard/ballot.py
  src/electionguard/data_store.py
  src/electionguard/decryption_mediator.py
  src/electionguard/election.py
  src/electionguard/guardian.py
  src/electionguard/key_ceremony_mediator.py
  src/electionguard/publish.py
  src/electionguard/serializable.py
  src/electionguardtest/ballot_factory.py
  src/electionguardtest/election.py
  src/electionguardtest/election_factory.py
  src/electionguardtest/sample_generator.py
  tests/integration/test_end_to_end_election.py
  tests/integration/test_hamilton_county_election.py
  tests/test_ballot.py
  tests/test_group.py
  tests/test_publish.py
Labels: documentation
