Repository microsoft/electionguard-python, pull requests merged in 2020-10, with the labels that each got.

#213 Use consistent tracking code format
  src/electionguard/group.py
  src/electionguard/tracker.py
  src/electionguard/words.py
  tests/test_tracker.py
Labels: enhancement

#224 Fixed a typo
  docs/Build_and_Run.md
Labels: community, hacktoberfest-accepted

#183 Fix / No import of generic T in utils #167
  src/electionguard/data_store.py
  src/electionguard/scheduler.py
  src/electionguard/serializable.py
  src/electionguard/utils.py
Labels: community, hacktoberfest-accepted

#185 Created method to reformat with black prior to linting.
  Makefile
Labels: community, hacktoberfest-accepted

#235 🔧 Lock cryptography version
  Pipfile
  Pipfile.lock
  src/electionguard/ballot.py
  src/electionguard/chaum_pedersen.py
  src/electionguard/data_store.py
  src/electionguard/decryption.py
  src/electionguard/decryption_mediator.py
  src/electionguard/decryption_share.py
  src/electionguard/election.py
  src/electionguard/election_object_base.py
  src/electionguard/election_polynomial.py
  src/electionguard/encrypt.py
  src/electionguard/group.py
  src/electionguard/guardian.py
  src/electionguard/hash.py
  src/electionguard/key_ceremony.py
  src/electionguard/key_ceremony_mediator.py
  src/electionguard/publish.py
  src/electionguard/scheduler.py
  src/electionguard/tally.py
  src/electionguard/tracker.py
  src/electionguardtest/ballot_factory.py
  src/electionguardtest/sample_generator.py
  tests/integration/test_end_to_end_election.py
  tests/test_decrypt_with_secrets.py
  tests/test_decryption_mediator.py
  tests/test_election_polynomial.py
  tests/test_elgamal.py
  tests/test_encrypt.py
  tests/test_encrypt_hypotheses.py
  tests/test_key_ceremony_mediator.py
  tests/test_nonces.py
  tests/test_publish.py
Labels: code owner only

#231 Cleanup tracker words
  src/electionguard/words.py
  tests/test_tracker.py
  tests/test_words.py
Labels: hacktoberfest-accepted

#234 🆙 Upgrade to 1.1.11
  setup.py
Labels: code owner only
